import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/presentation/widgets/app_card.dart';
import '../../../../core/theme/app_palette.dart';
import '../../../../core/theme/app_radii.dart';
import '../../../../core/theme/app_spacing.dart';
import '../../../categories/domain/entities/category.dart';
import '../../../categories/presentation/controllers/category_providers.dart';
import '../../../categories/presentation/widgets/category_icon.dart';
import '../../domain/entities/bill_status.dart';
import '../../domain/entities/bill_with_status.dart';
import 'bill_status_display.dart';

/// One bill in a list.
///
/// Shows what decides whether the reader needs to act: what it is, how much is
/// left, and when. The amount is the **outstanding** figure rather than the bill's
/// total, because a bill with ₱2,000 paid of ₱2,450 is a ₱450 problem, and the
/// total would overstate what is owed on every partially paid row.
///
/// ## Why most rows carry no badge
///
/// Every row used to end in a status chip. Twelve rows of chips is twelve pieces
/// of furniture and no information: "Upcoming" on a bill due in three weeks says
/// nothing the line above it has not already said, and a badge that appears
/// everywhere stops being read anywhere.
///
/// So a badge appears only where the status is not already obvious from the date:
/// overdue and due-soon, which are urgent, and part-paid, which the date cannot
/// convey at all. Everything else is left to the due line — and because those
/// rows are quiet, the ones that are not stand out without needing to shout.
///
/// A left rail carries the same signal in colour for the two urgent states. Two
/// cues rather than one, because colour alone is not information for everyone.
class BillListTile extends ConsumerWidget {
  const BillListTile({required this.item, required this.onTap, super.key});

  final BillWithStatus item;
  final VoidCallback onTap;

  /// Width of the coloured edge on an urgent row.
  static const double _railWidth = 4;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final AppPalette colors = context.colors;
    final TextTheme textTheme = Theme.of(context).textTheme;

    // Categories are already loaded for the picker; a row with no category, or
    // one whose category has since been deleted, simply shows no icon.
    final Category? category = switch (ref.watch(categoriesProvider)) {
      AsyncData<List<Category>>(value: final List<Category> all) =>
        all.where((Category c) => c.id == item.bill.categoryId).firstOrNull,
      _ => null,
    };

    final Color? rail = switch (item.status) {
      BillStatus.overdue => colors.overdue,
      BillStatus.dueSoon || BillStatus.dueToday => colors.dueSoon,
      _ => null,
    };

    return AppCard(
      onTap: onTap,
      // Zero, so the rail can reach the card's edges. The inner padding is
      // supplied below instead.
      padding: EdgeInsets.zero,
      child: Row(
        children: <Widget>[
          // The rail occupies the same width whether or not it is coloured, so a
          // quiet row and an urgent one align down the list.
          Container(
            width: _railWidth,
            height: 72,
            decoration: BoxDecoration(
              color: rail ?? Colors.transparent,
              borderRadius: const BorderRadius.horizontal(
                left: Radius.circular(AppRadii.md),
              ),
            ),
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(
                AppSpacing.md,
                AppSpacing.lg,
                AppSpacing.lg,
                AppSpacing.lg,
              ),
              child: Row(
                children: <Widget>[
                  if (category case final Category value) ...<Widget>[
                    CategoryIcon(category: value, size: 44),
                    const SizedBox(width: AppSpacing.md),
                  ],
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Row(
                          children: <Widget>[
                            Flexible(
                              child: Text(
                                item.bill.name,
                                maxLines: 1,
                                overflow: TextOverflow.ellipsis,
                                style: textTheme.titleMedium?.copyWith(
                                  color: colors.textPrimary,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                            ),
                            // Generated by a schedule, not typed by hand.
                            //
                            // `recurring_bill_id` was set by the generator from
                            // the day it existed and rendered nowhere, so a bill
                            // that reappears every month looked exactly like one
                            // somebody entered twice. An icon rather than a word:
                            // the row is already carrying a category, a date and
                            // a badge, and this is a footnote, not a status.
                            if (item.bill.recurringBillId != null) ...<Widget>[
                              const SizedBox(width: AppSpacing.xs),
                              Tooltip(
                                message: 'Repeats',
                                child: Icon(
                                  Icons.repeat_rounded,
                                  size: 14,
                                  color: colors.textTertiary,
                                ),
                              ),
                            ],
                          ],
                        ),
                        const SizedBox(height: AppSpacing.xxs),
                        Text(
                          // The category, then how soon. The category was
                          // previously only implied by the icon's colour, which
                          // is a guessing game for anyone who has not memorised
                          // thirteen hues — and it costs nothing to say.
                          _subtitle(item, category),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: textTheme.bodySmall?.copyWith(
                            color: switch (item.status) {
                              BillStatus.overdue => colors.overdueText,
                              BillStatus.dueSoon ||
                              BillStatus.dueToday => colors.dueSoonText,
                              _ => colors.textSecondary,
                            },
                            fontWeight: item.status?.needsAttention ?? false
                                ? FontWeight.w600
                                : FontWeight.w400,
                          ),
                        ),
                        // Only for a bill that is part paid. On any other row
                        // the bar would be either empty or full, which is two
                        // ways of saying what the words already said.
                        if (item.isPartiallyPaid) ...<Widget>[
                          const SizedBox(height: AppSpacing.sm),
                          _PaidBar(fraction: _paidFraction(item)),
                        ],
                      ],
                    ),
                  ),
                  const SizedBox(width: AppSpacing.md),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: <Widget>[
                      Text(
                        item.outstanding.format(),
                        style: textTheme.titleMedium?.copyWith(
                          color: item.status == BillStatus.paid
                              // A settled amount is history, not a demand.
                              ? colors.textTertiary
                              : colors.textPrimary,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      if (BillStatusDisplay.badge(item.status)
                          case final String label) ...<Widget>[
                        const SizedBox(height: AppSpacing.xxs),
                        Text(
                          label,
                          style: textTheme.labelSmall?.copyWith(
                            color: switch (item.status) {
                              BillStatus.overdue => colors.overdueText,
                              BillStatus.dueSoon ||
                              BillStatus.dueToday => colors.dueSoonText,
                              _ => colors.infoText,
                            },
                            fontWeight: FontWeight.w700,
                            letterSpacing: 0.3,
                          ),
                        ),
                      ],
                    ],
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// The category and how soon, or just how soon when there is no category.
  static String _subtitle(BillWithStatus item, Category? category) {
    final String due = _due(item);

    return category == null ? due : '${category.name} · $due';
  }

  /// How much of the bill has been paid, as a fraction.
  static double _paidFraction(BillWithStatus item) {
    final int total = item.bill.amount.minorUnits;

    return total <= 0 ? 0 : item.paid.minorUnits / total;
  }

  /// How soon, in words, counted against the row's own `today` — never the device
  /// clock. See [BillWithStatus.today].
  static String _due(BillWithStatus item) {
    if (item.status == BillStatus.paid) {
      return 'Settled';
    }

    return switch (item.daysUntilDue) {
      0 => 'Due today',
      1 => 'Due tomorrow',
      final int days when days < 0 => '${-days} days overdue',
      final int days => 'Due in $days days',
    };
  }
}

/// How much of a part-paid bill has been cleared.
///
/// Thin and unlabelled: the figures are already on the row, and this only has to
/// answer "roughly how far along" at a glance. A percentage in text here would be
/// a fourth number competing with three that matter more.
class _PaidBar extends StatelessWidget {
  const _PaidBar({required this.fraction});

  final double fraction;

  static const double _height = 4;

  @override
  Widget build(BuildContext context) {
    final AppPalette colors = context.colors;

    return Semantics(
      label: 'Paid',
      value: '${(fraction * 100).round()} percent',
      child: ClipRRect(
        borderRadius: AppRadii.round,
        child: SizedBox(
          height: _height,
          child: Stack(
            children: <Widget>[
              ColoredBox(color: colors.surfaceMuted),
              FractionallySizedBox(
                widthFactor: fraction.clamp(0.0, 1.0),
                child: DecoratedBox(
                  decoration: BoxDecoration(color: colors.primary),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
